export default {
  colors: {
    blackOne: '#000000',
    blackTwo: '#2B2B2B',
    white: '#FFFFFF',
    creamy: '#F8F8F8',
    yellowOne: '#FEED00',
    yellowTwo: '#FFED00',
    greyOne: '#E3E3E3',
    greyTwo: '#757575',
    greyThree: '#6E6E6E',
    greyFour: '#C3C2C2',
  },
  fontSize: {
    xxxxs: 10,
    xxxs: 11,
    xxs: 12,
    xs: 13,
    sm: 14,
    md: 15,
    xl: 16,
    xxl: 24,
    xxxl: 30,
  },
  fontFamily: {
    clanProNarrBlack: 'ClanPro-NarrBlack',
    clanPro: 'Clan Pro',
    clanProNarrBold: 'ClanPro-NarrBold',
  },
  breakpoints: {
    xl: 1200,
    md: 992,
    sm: 768,
    xs: 576,
  },
};
